spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:5432/postgres?sslmode=require}
    username: ${SPRING_DATASOURCE_USERNAME:postgres.eoqqdjxbazyrzusixccu}
    password: ${SPRING_DATASOURCE_PASSWORD:8I44VsaBHB8XJBWA}
